### ISSUE TITLE
workflow form for article

### ISSUE THREAD

**Issue by cziaarm** [ULCC/dart_hyrax#2]

**Comment by ghost** [comment]
Draft data model (in progress): https://docs.google.com/document/d/1ddfN96a8lsy8mM-BLcJ-Cj7TOnnwI0gDBwCOUmmewgU/edit?usp=sharing

**Comment by ghost** [comment]
Models in fork of dlibhydra: https://github.com/geekscruff/dlibhydra/tree/hyrax_jal
Views, presenters and search config in branch called ja_wip: https://github.com/ULCC/hyrax_ulcc/tree/ja_wip (work in progress)

**Comment by ghost** [comment]
Closing as basic working form is done. Rest of work moved into individual issues.
