### ISSUE TITLE
Run on centOS

### ISSUE THREAD

**Issue by cziaarm** [ULCC/dart_hyrax#3]
Can we run #hyrax on #centos

**Comment by ghost** [comment]
See https://atlas.hashicorp.com/centos/boxes/7

Durham run CentOS , as I think do Hull.

**Comment by ghost** [comment]
See e584d39 - Vagrantfile and script for running this app in centOS 

Further testing required, so leaving open for now.

**Comment by cziaarm** [comment]
Rightio, Next week I'm going to use this with hyper-v+centos on my surface. If it runs on that...

**Comment by ghost** [comment]
Made some changes today. This is deffo working with vagrant / virtualbox.
